### ISSUE TITLE
[OLD & NOT APPLICABLE] 로컬 개발 환경 구성에 어려움이 있는 독자분들은 docker를 시도해보세요.

### ISSUE THREAD

**Issue by appkr** [appkr/l5code#1]
> 이 문서는 더 이상 유효하지 않습니다. 이슈 목록에서 Docker 문서를 참고해주세요.

---

도커 환경을 시도해 보세요. 이 저장소의 docker 브랜치에 자세한 설명이 담겨 있습니다.

https://github.com/appkr/l5code/tree/docker/docker

**Comment by corean** [comment]
[Valet](https://laravel.kr/docs/5.3/valet)이 osx, linux만 지원하긴 하지만, 굉장히 편한것 같아요.
