### ISSUE TITLE
데이터베이스 마이그레이션 및 시딩 과정에서 에러 발생

### ISSUE THREAD

**Issue by BestCoCo** [appkr/l5code#13]
안녕하세요.

책에 있는 과제를 따라하고 설치하는 과정에서 다음과 같은 오류가 발생합니다.
일단 오류를 무시하고 진행해도, 실행은 문제 없습니다만, 해당 오류가 발생되는 이유와, 해결 방안이 있는지요?

환경은 MAC Sierra 이며,
3.3 데이터베이스 마이그레이션 및 시딩 부분입니다

오류 메시지

CoCo-MacBook-Pro:books coco$ php artisan migrate --seed --force
Nothing to migrate.
Seeded: tags table
Seeded: UsersTableSeeder
Seeded: ArticlesTableSeeder
Seeded: article_tag table
Downloading 10 images from lorempixel. It takes time...
File saved: f7c9cc204ba92130b9e691b0df0e659f.jpg
File saved: d9a61a01f10b5bba8984c656260efdad.jpg
File saved: 0ee757598698325be09097a43bcd5555.jpg
File saved: d89121b6f92ee37b0f79971334f80cd4.jpg
File saved: 5ce2fd51c17741bb5fe3a0d4c1a67bb4.jpg
File saved: 1282d7c33267f150db270e3031db87f5.jpg

                                        
  [ErrorException]                      
  finfo_file(): Empty filename or path

**Comment by appkr** [comment]
@BestCoCo 일시적인 증상으로 보이는데, 다시 해도 그런가요? 앞에 파일을 여섯개나 받았다는 얘기는 런타임 환경이나 코드의 문제는 아닌 것으로 추정되고, 일시적인 네트워크 통신 문제이거나, 로렘 픽셀에서 제공하는 이미지의 문제일 가능성이 큽니다.

다시 해도 문제가 지속된다면, 문제가 발생했을 때 storage/logs/laravel.log 파일의 로그를 살펴보시고, 문제를 해결할 수 없다면, https://wiki.modernpug.org/questions 에 이 이슈의 링크와 잡은 실행로그를 같이 올려서 다시 한번 질문해 주세요.

고맙습니다.
