### ISSUE TITLE
php7.0 < 가 필요하지 않을까요?

### ISSUE THREAD

**Issue by pronist** [appkr/l5code#17]
```bash
laravel new myapp
``` 
명령으로 라라벨 기본 프로젝트를 생성하고 **aws-ubuntu 18.04 LTS** 에서 

provision.sh
serve.sh

스크립트를 실행하고 라라벨을 돌리면 제대로 작동하지 않습니다.
그래서 일단 프로비저닝 스크립트에 존재하는 php 를 몽땅 7.2로 올려서
재 인스톨한 뒤, nginx 설정을 php7.2 로 바꾸었더니
라라벨이 정상실행 되었습니다.

치명적인 오류는 없었으나, 쉘 스크립트 실행 중
일부 패키지나 파일을 못 찾는 등의 오류가 있었습니다.

composer install 실행 시 프로비저닝으로 구성된 php7.0으로 돌리면
의존성 에러가 발생합니다.

php 버전의 업그레이드가 필요하지 않을까요?

아니면 그냥 composer.json 에서 php 버전을 낮추면 되는건가용?

**Comment by appkr** [comment]
@pronist 예 맞습니다. 

- 라라벨 5.7은 PHP 7.1.3이 필요합니다. https://github.com/laravel/laravel/blob/master/composer.json#L8
- 라라벨 5.6은 PHP 7.1.3이 필요합니다. https://github.com/laravel/laravel/blob/5.6/composer.json#L8
- 라라벨 5.5 이하는 PHP 7.0.x이 필요합니다. https://github.com/laravel/laravel/blob/5.5/composer.json#L8

설치하려는 라라벨 버전에 맞추어 적절한 PHP 버전을 설치하시면 됩니다.

저는 `p`라는 이름의 Bash 함수를 만들어서 PHP 버전을 전환하고 있습니다.
https://github.com/appkr/dotfiles/blob/master/.functions#L277-L295
[![asciicast](https://asciinema.org/a/208790.png)](https://asciinema.org/a/208790)

**Comment by pronist** [comment]
PHP 7.2 에서 **php7.2-mcrypt** 모듈은 **Deprecated** 되어 설치가 안 되는 것을 파악했습니다. 따라서 **provision.sh** 에서 주석처리 하니 잘 설치됩니다. 감사합니다. 👍
